version: '2'
services:
  runtime:
    image: johncclayton/charger-build
    container_name: "charger"

    restart: unless-stopped

    ports:
      - "5000:5000"

    volumes:
      - data:/data

    networks:
      - net

  sync:
    image: johncclayton/syncthing-build
    container_name: "syncthing"

    restart: unless-stopped

    ports:
      - "8384:8384"

    volumes:
      - data:/data

    networks:
      - net

volumes:
  data:
    external: false

networks:
  net:
  

